version: '3.8'

services:
  app:
    build: .
    entrypoint: .docker/entrypoint.sh
    container_name: app
    ports:
      - 3333:3333
    volumes:
      - .:/home/node/app
    depends_on:
      - db
      - redis
    networks:
      - app-network

  db:
    build: .docker/postgres
    container_name: db
    restart: always
    tty: true
    ports:
      - 5432:5432
    volumes:
      - .docker/dbdata:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=docker
    networks:
      - app-network

  redis:
    image: 'bitnami/redis:latest'
    container_name: redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    tty: true
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - 8000:80
    depends_on:
      - db

networks:
  app-network:
    driver: bridge
